import os
from building import *

cwd = GetCurrentDir()

# 源文件
src = Glob('*.c')
src += Glob('lvgl_v8/generated/*.c')
src += Glob('lvgl_v8/generated/images/*.c')
src += Glob('lvgl_v8/generated/guider_fonts/*.c')
src += Glob('lvgl_v8/custom/*.c')

# 头文件路径
path = [cwd]
path += [os.path.join(cwd, 'lvgl_v8', 'generated')]
path += [os.path.join(cwd, 'lvgl_v8', 'generated', 'images')]
path += [os.path.join(cwd, 'lvgl_v8', 'generated', 'guider_fonts')]
path += [os.path.join(cwd, 'lvgl_v8', 'generated', 'guider_customer_fonts')]
path += [os.path.join(cwd, 'lvgl_v8', 'custom')]

group = DefineGroup('Applications', src, depend=[''], CPPPATH=path)

Return('group')
